### ISSUE TITLE
TP Nº1

### ISSUE THREAD

**Issue by lucianovilla** [AuditoriaTICS/BARRICAS#1]
Actividad:
1) Realizar definiciones de auditoría. Investigar, citando las fuentes, otras definiciones.
2) ¿Cuáles son los Objetivos de la Auditoría?
3) ¿Qué importancia tiene la Auditoría?

@andresmartinezf

Desarrollo

1)- Definición de AUDITORÍA
Concepto N°1: La AUDITORÍA según:
William Thomas Porter y John C. Burton definen la Auditoria como el examen de la informacion por una tercera persona distinta de quien la prepara y del usuario, con la intencion de establecer su veracidad; y el dar a conocer los resultados de este examen, con la finalidad de aumentar la utilidad de tal informacion para el usuario.
Arthur W. Holmes obtiene como conclusion en su concepto moderno  que la Auditoria es "el examen critico y sistematico de la actuacion y los documentos financieros y juridicos en que se refleja, con la finalidad de averiguar la exactitud, integridad y autenticidad de los mismos.
El Instituto Norteamericano de Contadores Públicos (AICPA), tiene como definición de Auditoría:  Un examen que pretende servir de base para expresar una opinion sobre la razonabilidad, consistencia y apego a los principios de contabilidad generalmente aceptados, de estados financieros preparados por una empresa o por otra entidad para su presentacion al Publico o a otras partes interesadas.
Fuente: http://fccea.unicauca.edu.co/old/tgarf/tgarfse1.html
Concepto N°2: La AUDITORÍA es definida por La Ley de Auditoría de Cuentas (LAC) y su Reglamento  como la actividad consistente en la revisión y verificación de las cuentas anuales, así como de otros estados financieros o documentos contables, elaborados con arreglo al marco normativo de información financiera que resulte de aplicación, siempre que aquélla tenga por objeto la emisión de un informe sobre la fiabilidad de dichos documentos que puede tener efectos frente a terceros.
Fuente: PDF Auditoria: Ed. Mc Graw Hill.
2)- Objetivos de la AUDITORÍA
OBJETIVO PRINCIPAL DE LA AUDITORIA:
El objetivo principal de una Auditoria es la emision de un diagnostico sobre un sistema de informacion empresarial, que permita tomar decisiones sobre el mismo. Estas decisiones pueden ser de diferentes tipos respecto al area examinada y  al usuario del dictamen o diagnostico.
OBJETIVOS BÁSICOS:
•	Descubrir fraudes.
•	Descubrir errores de principio.
•	Descubrir errores tecnicos.
 
El avance tecnologico experimentado en los ultimos tiempos en los que se ha denominado la "Revolucion Informatica", asi como el progreso experimentado por la administracion de las empresas actuales y la aplicacion a las mismas de la Teoria General de Sistemas, ha llevado a Porter y Burton a adicionar tres nuevos objetivos :
•	Determinar si existe un sistema que proporcione datos pertinentes y fiables para la planeacion y el control.
•	Determinar si este sistema produce resultados, es decir, planes, presupuestos, pronosticos, estados financieros, informes de control dignos de confianza, adecuados y suficientemente inteligibles por el usuario.
•	Efectuar sugerencias que permitan mejorar el control interno de la entidad.
Fuente: http://fccea.unicauca.edu.co/old/tgarf/tgarfse2.html
3)- Importancia de la AUDITORÍA
La calidad es una ventaja competitiva para aquellas empresas que se han identificado con ella y en donde la gerencia se encuentra plenamente identificada con su alcance, repercusiones, con todo lo que ello puede generar.    
Una vez que se ha inculcado obliga a la gerencia estar atenta sobre su comportamiento, cuidando, la forma como se está manteniendo, su alcance, logros, así como sus debilidades.    
Por tanto, la Auditoria de la calidad es una importante actividad que permite a las organizaciones mejorar sus funciones en forma continua. La auditoria puede ser tanto interna o externa a la organización.
Fuente: PDF Institución Universitaria Escolme.
[Auditoria TP-N1.docx](https://github.com/AuditoriaTICS/BARRICAS/files/464314/Auditoria.TP-N1.docx)

**Comment by lucianovilla** [comment]
Actividad:
4) Realizar una síntesis de los Antecedentes de Auditoría
5) Describir las diferentes Clases de Auditorías y sus diferentes puntos de vista
6) ¿Qué es el Peritaje Informático?

@armoaivana

**Comment by lucianovilla** [comment]
Actividad:

7) Describir el Perfil del ASI como Auditor
8) ¿Qué conocimientos debe tener el ASI como auditor?
9) Realizar una descripción de Auditoría de Tecnologías de Información y Comunicación (TIC)
@

**Comment by lucianovilla** [comment]
hicieron los puntos?? @andresmartinezf @armoaivana

**Comment by lucianovilla** [comment]
Actividad:

7) Describir el Perfil del ASI como Auditor.
8) ¿Qué conocimientos debe tener el ASI como auditor?.
9) Realizar una descripción de Auditoría de Tecnologías de Información y Comunicación (TIC).

                                                                        Desarrollo

7) El ASI audita el funcionamiento de la empresa examinando la captura y procesamiento de los datos como los resultados obtenidos para mejorar los procesos de la organización. Requiere tener la habilidad para cualquier tipo de persona así como un excelente manejo de la PC.
 Los papeles que debe cumplir son:
•como consultor: es contratado por la empresa para aportar ideas frescas que no poseen los demás.
•como especialista de apoyo: trabaja en la empresa de manera regular, dispone
experiencia de software y hardware, no esta encargado de proyectos.
•como agente de cambio: es el de mayor responsabilidad, ya que desarrolla el plan y colabora para agilizarlo.
8) Conocimientos básicos que debe poseer un ASI como auditor:

• Desarrollo informático; gestión de proyectos y del ciclo de vida de un proyecto de desarrollo.
• Gestión del departamento de sistemas.
• Análisis de riesgos en un entorno informático.
• Sistema operativo (este aspecto dependerá de varios factores, pero principalmente de si va a trabajar en un entorno único -auditor interno- o, por el contrario, va a tener posibilidades de trabajar en varios entornos como auditor externo).
• Telecomunicaciones.
• Gestión de bases de datos.
• Redes locales.
• Seguridad física.
• Operaciones y planificación informática; efectividad de las operaciones y del rendimiento de los sistemas.

9) La Auditoria de las TIC está adquiriendo cada vez mayor relevancia, debido a la
cada vez mayor importancia y protagonismo de los sistemas informáticos en todos los ámbitos de
nuestra Sociedad. Estas auditorías ayuda a las organizaciones a evaluar la manera en que hacen sus negocios o proveen sus servicios apoyados por TIC, buscando proteger los intereses del Estado, de los Trabajadores y de los Clientes.
Actualmente, las Empresas y Organismos depositan en sus Sistemas de Información la responsabilidad de gestionar de forma eficaz y eficiente sus transacciones de negocio. Los procesos manuales son cada vez menos frecuentes y en la práctica se observa que la casi totalidad de las empresas hacen uso de la enorme capacidad de proceso, gestión y comunicación disponibles, todo ello a precios cada vez más asequibles a Organizaciones de todos los tamaños.
Estas Auditorías permiten validar la seguridad, confiabilidad, integridad y privacidad de los
sistemas de información. Dada la dependencia creciente de las organizaciones en las TIC y el surgimiento de normativa para su buen gobierno, el auditor interno también trabaja como consejero empresarial, asesorando en cuanto al establecimiento de políticas y estándares que aseguren la información y el control de las TIC.
En conclusión se podría decir que las Tecnologías de la Información y Comunicación exige al mundo empresarial un accionar más efectivo en relación con el ordenamiento de los mecanismos de control interno sin desvirtuar su esencia.

**Comment by lucianovilla** [comment]
@AlfredoCabello como siempre tarde, pero ya te vamos a dar unos puntos para que hagas

**Comment by armoaivana** [comment]
Actividad:
4) Realizar una síntesis de los Antecedentes de Auditoría
5) Describir las diferentes Clases de Auditorías y sus diferentes puntos de vista
6) ¿Qué es el Peritaje Informático?
Desarrollo:
4) Los antecedentes de la auditoría podemos encontrarlos en civilizaciones preocupadas en controlar
los gastos y los ingresos del Estado, para vigilar el manejo de los fondos por los funcionarios
Asignados. Entre estas civilizaciones tenemos la cultura egipcia.
Durante el reinado de Eduardo I de Inglaterra, a fines del siglo XIII, se acuña el vocablo auditor
como denominación propia de la persona encargada de realizar los controles de cuentas.
Las actuales asociaciones profesionales de auditores tuvieron sus precursores en los Consejos
Londinenses de Londres (1310), el Colegio de Contadores de Venecia (1581), el Tribunal de
Cuentas de París (1640) y la "Academia dei Ragioneri" de Milán y Bolonia (1658).
El concepto moderno de auditoría contable surge con los fracasos financiero económicos de las
sociedades de acciones nacidas de la revolución industrial, en la segunda mitad del siglo XVIII.
Falta de seriedad y de profesionalidad en sus gestores provocó la quiebra de una gran número de
Empresas. Esta situación dio lugar a la imposición tácita, y posteriormente legal, de revisiones de
la situación financiera de las empresas a cargo de contables independientes.
El gobierno británico El gobierno británico
Aprobó oficialmente la creación del Instituto de Auditores Titulados de Inglaterra y Gales, en 1880.
En 1929 se efectuó una revisión a cargo del
American Institute of Certified Public Accountants(AICPA). En 1934 se publica un documento
Conjunto entre el AICPA y la recién , creada "Securities and Exchange Commission" (SEC): " Audit of
Corporate Accounts".
En 1939 se establece las primeras acciones para la definición de las Normas de Auditoría
Generalmente Aceptadas (NAGA), mediante la creación de un Comité especial sobre
Procedimientos de Auditoría en el AICP A.
La documentación fruto de los trabajos de este Comité
Se denominó "Extensions of Auditing Procedure" (mayo de 1939), que posteriormente Paso a
denominarse "Statements on Auditing Procedure" (SAP). Hasta 1972 se publicaron un total de 54
SAP.
En 1972, el comité pasa a llamarse "Comité Ejecutivo de Normas de Auditoría", cuya misión es la
Interpretación de las NAGA, produciendo los "Statements on Auditing Standard" (SAS). A partir de
1978, el "Auditing Standard Board" (AICPA) es el responsable de la promulgación de normas y
procedimientos de auditoría para los miembros del AICPA
En España no se empieza a considerar la aplicación y desarrollo de la auditoría hasta la publicación
del Código de Comercio (Ley 21/7/73) [7].
En 1943 se crea el Instituto de Censores Jurados de Cuentas, institución profesional privada que
agrupa a los profesionales dedicados a la censura de cuentas, precedente de la auditoría de
cuentas.
Con la constitución y posterior desarrollo de la Comunidad Económica Europea, se ha tratado de
armonizar y estandarizar las normas de auditoría de los países miembros, a través de las directivas
y de los reglamentos, publicadas desde 1968.
a partir de 1988, se realiza una
paulatina adaptación del ordenamiento mercantil con la promulgación de varias leyes y decretos,
Como la Ley de Auditoría de Cuentas (12/7/88) [26], el Texto Refundido de la Ley de Sociedades
Anónimas (22/12/89) y el Plan General de Contabilidad (20/12/90) [37], entre los más
importantes.
6) Se conoce como peritaje informático a los estudios e investigaciones orientados a la obtención de una prueba informática de aplicación en un asunto judicial para que sirva a un juez para decidir sobre la culpabilidad o inocencia de una de las partes.

**Comment by AlfredoCabello** [comment]
5) Describir las diferentes Clases de Auditorias y sus diferentes puntos de vista.
Clases de auditoria
 La Auditoria puede clasificarse desde diversos puntos de vista, según el sujeto que la efectúa, según el contenido y los fines, por su amplitud y por su frecuencia.
Por el sujeto que la efectúa:
• Auditoria interna: Está a cargo de empleados de la propia empresa, encuadrados en un departamento directamente dependiente de la dirección general.
• Auditoria externa: Está a cargo de auditores profesionales, ajenos a la empresa y totalmente independientes.

Por su contenido y fines:
• Auditoria de gestión: Afecta a la situación global de la empresa. es aquella que se se realiza para evaluar el grado de eficiencia y eficacia en el logro de los objetivos previstos por la organización y con los que se han manejado los recursos.
• Auditoria organizativa: Analiza si la estructura organizativa de la empresa es la adecuada, según las necesidades y problemas de la misma.
• Auditoria operacional: Para determinar hasta qué punto una organización, una unidad o función dentro de una organización, está cumpliendo los objetivos establecidos por la gerencia; así como identificar las condiciones que necesiten mejora.
• Auditoria financiera: Examen y verificación de los estados financieros de la empresa, para emitir una opinión fundada sobre el grado de fiabilidad de dichos estados.
• Auditoria contable: Analiza la adecuación de los criterios empleados para recoger los hechos derivados de la actividad de la empresa y su representación, mediante apuntes contables.
• Auditoria informática: Examen y verificación del correcto funcionamiento y control del sistema informático de la empresa.

Por su amplitud:
• Auditoria total: Afecta a todos los elementos de la empresa.
• Auditoria parcial: Se concentra en determinados elementos de la empresa.

Por su frecuencia:
• Auditoria permanente: Se realiza periódicamente a lo largo del ejercicio económico
•Auditoria ocasional: Se realiza de forma esporádica.
