### ISSUE TITLE
Carta Presentacion

### ISSUE THREAD

**Issue by lucianovilla** [AuditoriaTICS/BARRICAS#2]

**Comment by AlfredoCabello** [comment]
2016-09-28 17:31 GMT-03:00 andresmartinezf <notifications@github.com>:

**Comment by AlfredoCabello** [comment]
2016-09-28 21:01 GMT-03:00 Alfredo Cabello <alfredocabello92@gmail.com>:

**Comment by villagar** [comment]
[Carta.De.Presentacion.docx](https://github.com/AuditoriaTICS/BARRICAS/files/509417/Carta.De.Presentacion.docx)

**Comment by villagar** [comment]
[Carta.De.Presentacion.docx](https://github.com/AuditoriaTICS/BARRICAS/files/509421/Carta.De.Presentacion.docx)
